### ISSUE TITLE
fly.toml gets overwritten when running launch command twice

### ISSUE THREAD

**Issue by Johannes-Werbrouck** [fly-apps/fly-laravel#21]
We have to decide if this is wanted behaviour or not. I'd propose printing an error and stopping the command when there's already a fly.toml file present, or perhaps ask if the user just wants to deploy instead? Curious to see what you guys think.

**Comment by KTanAug21** [comment]
We can do both, Print out an error message saying a fly.toml exists so we cant do a launch, and prompt if the user want to deploy instead, then if the answer is yes. the cli deploys
