### ISSUE TITLE
Could we autogenerate safe passwords for mysql? 

### ISSUE THREAD

**Issue by Johannes-Werbrouck** [fly-apps/fly-laravel#39]
Wondering what is the best UX: have the user enter the password and root password for the mysql database, or just autogenerating safe passwords for these. They get set automatically in the mysql secrets and in the laravel app secrets

**Comment by fideloper** [comment]
I vote for generating them automatically and setting them as a secrets.

**Comment by Johannes-Werbrouck** [comment]
Fixed with #40
