### ISSUE TITLE
Should we ask for the organization when launching MySQL and Redis?

### ISSUE THREAD

**Issue by Johannes-Werbrouck** [fly-apps/fly-laravel#44]
The networking between Laravel and the database applications is based on the .internal address, which will require the apps to be in the same organization. Does it still make sense to ask for the organization when launching a MySQL or Redis app if they will not work with the Laravel app if the organization differs? 

We could just get the organization from the Laravel app and always launch in the same organization. 

What do you guys think? @fideloper @KTanAug21

**Comment by KTanAug21** [comment]
Hi @Johannes-Werbrouck! There are two scenarios here: 
1. The Laravel web fly app is detected - in which case, it would make sense to use the detected Laravel fly app's organization
2. No Laravel web fly app is detected - in which case the organization should be prompted for
