### ISSUE TITLE
Use the directory name as default app name

### ISSUE THREAD

**Issue by Johannes-Werbrouck** [fly-apps/fly-laravel#9]
Usually, the directory name will also be the app name. So, we should use the directory name as the default app name on fly instead of generating a random one.

**Comment by KTanAug21** [comment]
Hi @Johannes-Werbrouck ! Using the directory as the app name may not be the best approach, as the directory name may be associated with an existing fly app. That would throw the following error: ```Error: Validation failed: Name has already been taken```

Which would be weird in user's pov, as I've already given the task of generating a name to the cli, so why should it not generate a valid name?
